server:
  port: 8092

spring:
  datasource:
    url: jdbc:h2:mem:conference
    driverClassName: org.h2.Driver
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console
  doc:
    api-docs:
      path: /api-docs
  springfox:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
