server:
  port: 8091

spring:
  datasource:
    url: jdbc:h2:mem:conference
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    headers:
      frame: false
spring-security:
  permit-uris: ${SPRING_SECURITY_PERMIT_URIS:'/actuator/health,/swagger-ui/**,/v3/api-docs/**,/swagger-resources/**,/h2-console/**}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
